# Cloud Build configuration for automated deployments
# Triggered by GitHub pushes or manual builds

steps:
  # Build API image
  - name: "gcr.io/cloud-builders/docker"
    id: "build-api"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/rag-api:${SHORT_SHA}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/rag-api:latest"
      - "-f"
      - "Dockerfile.api"
      - "."

  # Build UI image
  - name: "gcr.io/cloud-builders/docker"
    id: "build-ui"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/rag-ui:${SHORT_SHA}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/rag-ui:latest"
      - "-f"
      - "Dockerfile.ui"
      - "."

  # Build ETL image
  - name: "gcr.io/cloud-builders/docker"
    id: "build-etl"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/rag-etl:${SHORT_SHA}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/rag-etl:latest"
      - "-f"
      - "Dockerfile.etl"
      - "."

  # Push images to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "push-api"
    args:
      [
        "push",
        "--all-tags",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/rag-api",
      ]
    waitFor: ["build-api"]

  - name: "gcr.io/cloud-builders/docker"
    id: "push-ui"
    args:
      [
        "push",
        "--all-tags",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/rag-ui",
      ]
    waitFor: ["build-ui"]

  - name: "gcr.io/cloud-builders/docker"
    id: "push-etl"
    args:
      [
        "push",
        "--all-tags",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/rag-etl",
      ]
    waitFor: ["build-etl"]

  # Deploy API to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-api"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "rag-api"
      - "--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/rag-api:${SHORT_SHA}"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
    waitFor: ["push-api"]

  # Deploy UI to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-ui"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "rag-ui"
      - "--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/rag-ui:${SHORT_SHA}"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
    waitFor: ["push-ui", "deploy-api"]

  # Deploy ETL to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-etl"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "rag-etl"
      - "--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/rag-etl:${SHORT_SHA}"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--no-allow-unauthenticated"
    waitFor: ["push-etl"]

# Substitution variables
substitutions:
  _REGION: us-central1
  _REPO_NAME: rag-system

options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s # 30 minutes

